global.text_data_en = ds_map_create();
ds_map_add(global.text_data_en, "obj_battlecontroller_286", "* YOU WON!&* You earned \\[1] EXP and \\[2] gold.");
ds_map_add(global.text_data_en, "obj_battlecontroller_287", "&* Your LOVE increased.");
ds_map_add(global.text_data_en, "recover_hp", "* You recovered \\[1] HP!/%");
ds_map_add(global.text_data_en, "recover_hp_max", "* Your HP was maxed out./%");
ds_map_add(global.text_data_en, "item_menub_header", "   * ");
ds_map_add(global.text_data_en, "item_menub_page1", "                     PAGE 1");
ds_map_add(global.text_data_en, "item_menub_page2", "                     PAGE 2");
ds_map_add(global.text_data_en, "battle_mercy_spare", "   * Spare");
ds_map_add(global.text_data_en, "battle_mercy_flee", "   * Flee");
ds_map_add(global.text_data_en, "battle_name_header", "   * ");
ds_map_add(global.text_data_en, "battle_name_a", " A");
ds_map_add(global.text_data_en, "battle_name_b", " B");
ds_map_add(global.text_data_en, "battle_name_c", " C");
ds_map_add(global.text_data_en, "SCR_TEXT_111", "   * I'm outta here.");
ds_map_add(global.text_data_en, "SCR_TEXT_112", "   * I've got better to do.");
ds_map_add(global.text_data_en, "SCR_TEXT_113", "   * Escaped...");
ds_map_add(global.text_data_en, "SCR_TEXT_114", "   * Don't slow me down.");
ds_map_add(global.text_data_en, "SCR_TEXT_121", "   * Ran away with \\[1] EXP&     and \\[2] GOLD.");
ds_map_add(global.text_data_en, "key_left", "[LEFT]");
ds_map_add(global.text_data_en, "key_right", "[RIGHT]");
ds_map_add(global.text_data_en, "monstername_68", "Sans");
ds_map_add(global.text_data_en, "obj_sansb_252", "what^1?&you think i'm just&gonna stand there&and take it?/%%");
ds_map_add(global.text_data_en, "SCR_TEXT_6689", "   * Check");
ds_map_add(global.text_data_en, "obj_sansb_1018", "* SANS 1 ATK 1 DEF&* The easiest enemy^1.&* Won't even deal damage./^");
ds_map_add(global.text_data_en, "monstername_10_1", "Mr. Sunshine");
ds_map_add(global.text_data_en, "monstername_10_2", "Abberant");
ds_map_add(global.text_data_en, "SCR_TEXT_10_1", "   * Check         * Skeptic&   * Brighten      * Clouden");
ds_map_add(global.text_data_en, "SCR_TEXT_10_2", "   * Check         * Cut Down");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_1", "Impossible!&I'll defeat&that&imposter!!");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_2", "SHUT UP!!!");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_3", "* MR. SUNSHINE - ATK 68 DEF 68&/");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_4", "* Believes he is the Sun, so he&  doesn't care to leave the&  UNDERGROUND./");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_5", "* (But, he is not really&  the Sun.)/^");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_6", "* You confessed that there is a&  bigger and more real SUN&  outside./^");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_7", "* You brighten the room with&  your smile./");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_8", "* Mr. Sunshine thinks it's&  a celestial body!/^");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_9", "* You clouden the room with&  cruel cynicism./");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_10", "* Mr. Sunshine thinks he's&  old news./^");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_11", "What? A&slice of&moon? Not&bad.");
ds_map_add(global.text_data_en, "obj_doghole_mrsunshine_12", "O, I've&been&eclipsed.");
